### ISSUE TITLE
Signup not working

### ISSUE THREAD

**Issue by wzr1337** [joleitner/cardano-car-documents#1]
Hi Jonas,

signing up a new user gives the following issue

```
<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1659963014214"></script><script src="/_next/static/chunks/webpack.js?ts=1659963014214" defer=""></script><script src="/_next/static/chunks/main.js?ts=1659963014214" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1659963014214" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1659963014214" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1659963014214" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1659963014214" defer=""></script><script src="/_next/static/development/_middlewareManifest.js?ts=1659963014214" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"></div><script src="/_next/static/chunks/react-refresh.js?ts=1659963014214"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{"__NEXT_PAGE":"/api/users"},"buildId":"development","isFallback":false,"err":{"name":"Error","message":"@prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.\nIn case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues","stack":"Error: @prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.\nIn case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues\n at new PrismaClient (/usr/src/app/node_modules/.prisma/client/index.js:3:11)\n at eval (webpack-internal:///(api)/./src/prisma.js:8:25)\n at Object.(api)/./src/prisma.js (/usr/src/app/.next/server/pages/api/users.js:307:1)\n at __webpack_require__ (/usr/src/app/.next/server/webpack-api-runtime.js:33:42)\n at eval (webpack-internal:///(api)/./src/models/users.js:12:65)\n at Object.(api)/./src/models/users.js (/usr/src/app/.next/server/pages/api/users.js:274:1)\n at __webpack_require__ (/usr/src/app/.next/server/webpack-api-runtime.js:33:42)\n at eval (webpack-internal:///(api)/./pages/api/users/index.js:8:75)\n at Function.__webpack_require__.a (/usr/src/app/.next/server/webpack-api-runtime.js:111:13)\n at eval (webpack-internal:///(api)/./pages/api/users/index.js:1:21)"},"gip":true,"scriptLoader":[]}</script></body></html>
```

I guess some `prisma generate` step is missing during setup

**Comment by wzr1337** [comment]
The actual error seems to be the following:

```shell
prisma-studio_1  | Prisma schema loaded from schema.prisma
prisma-studio_1  | Datasource "db": PostgreSQL database "cardano_cars", schema "public" at "db:5432"
prisma-studio_1  | 
prisma-studio_1  | Introspecting based on datasource defined in schema.prisma …
prisma-studio_1  | Error: P1000
prisma-studio_1  | 
prisma-studio_1  | Authentication failed against database server at `db`, the provided database credentials for `admin` are not valid.
prisma-studio_1  | 
prisma-studio_1  | Please make sure to provide valid database credentials for the database server at `db`.
prisma-studio_1  | 
prisma-studio_1  | 
prisma-studio_1  | Prisma schema loaded from schema.prisma
prisma-studio_1  | Prisma Studio is up on http://localhost:5555
```

1. I am using a clean checkout of the repo
2. I did run `docker prune --all`
3. I ONLY changed the bitfrost and pinata keys. in the `app/.env` file as suggested.
